### ISSUE TITLE
put or append in small chunks 

### ISSUE THREAD

**Issue by gsmachado** [EMCECS/atmos-client-java#1]
Hello @APeter0807 , all,

This is not an issue, it's more like a question about library's usability.

I need to use the AtmosApiClient to persist small chunks (like, ~4Mb) in the same key. I'm reading a large stream and then, I want to put small chunks to ATMOS. In this use case, an "appendObject" function would be nice... or, even, a putObject() with an offset. Using the S3 interface I could easily have that. But, I can't use such interface.

Do you have an example of how can I achieve that with the current implementation?

**Comment by twincitiesguy** [comment]
It's important to distinguish between Atmos the appliance and Atmos the API.  In the Atmos appliance, the S3 API is (by specification) WORM, so there is no ability to update objects.  However, in the Atmos API, you **can** update objects, including appending to them.  To append to an object, you would have to know its size first and this is not an atomic operation, so you would have to manage any threaded access.  This is [the call you would make](http://emcvipr.github.io/dataservices-sdk-java/atmos-client/latest/javadoc/com/emc/atmos/api/AtmosApi.html#updateObject(com.emc.atmos.api.ObjectIdentifier,%20java.lang.Object,%20com.emc.atmos.api.Range)) in the atmos-client library:

`atmosApi.updateObject( identifier, newData, new Range( firstByte, lastByte ) );`

(newData in this call is a byte array)

It may also interest you that our ECS appliance offers extensions to the S3 API that provide exactly what you're looking for, including an atomic append operation.

**Comment by gsmachado** [comment]
Thanks a lot for the answer!
