### ISSUE TITLE
Remove dependency on jersey

### ISSUE THREAD

**Issue by tdiesler** [EMCECS/atmos-client-java#3]
The use of jersey prevents this component to get integrated with [WildFly](http://wildfly.org/) and [RedHat EAP](https://developers.redhat.com/products/eap/overview/). Perhaps it'd be possible to use the standard APIs for JAX-RS communication?

CrossRef: https://github.com/wildfly-extras/wildfly-camel/issues/1984

**Comment by JoshDM** [comment]
Of note, a resolution to this issue on a broader scale is documented here:

https://stackoverflow.com/questions/11133844/jersey-client-throws-npe-in-clientresponse-getlastmodified

**Comment by twincitiesguy** [comment]
Unfortunately, Jersey 1.x is the only version that provides full request wrapping via filters.  We use this for automatic retries (there is no _reasonable_ way to do that in generic JAX-RS or in Jersey 2.x -- but we are open to suggestions).  I would love to drop our dependency on the older library, but quite frankly, in the vast majority of deployments, it works quite well.

Given the above 4 methods proposed by @JoshDM:
* Method 1 we have no control over
* Method 2 I think justifies a PR to the jersey repo (ahem.. Josh)
* We will implement Method 3 in the next release
* Method 4 is a downstream workaround, which should be unnecessary after the above-mentioned release

**Comment by JoshDM** [comment]
"(ahem... Josh)"

Stu, you know I'm super-busy; plus I've got a work-around.  I'll leave it to you or tdiesler to follow-up with the Jersey folks, who might jsut kick it back as an issue with JBoss since Method 1 exists.

**Comment by twincitiesguy** [comment]
Ok.  Just figured since you already had the code in the above comment, it wouldn't take very long to paste it into a fork.

**Comment by JoshDM** [comment]
Of jersey or of EMCECS

**Comment by twincitiesguy** [comment]
Well, then I will leave it to our users.  Should anyone want to pursue this change in Jersey 1, feel free to open a PR with the above (Method 2) suggestion.

**Comment by twincitiesguy** [comment]
Method 3 above has been implemented and released on 3.0.2.  I'm closing the issue as this should be a sufficient workaround.
